# version string format
version: "{build}"

image: Visual Studio 2017

# clone directory
clone_folder: C:\projects\erkir

init:
    - git config --global core.autocrlf input

# branches to build
branches:
    # whitelist
    only:
        - master

platform:
    - Win32
    - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
    - Debug
    - Release

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
    - cd C:\projects\erkir\test
    - cl /I..\src /I..\include /W4 /EHsc test.cpp /link /out:test.exe

test_script:
    - cd C:\projects\erkir\test
    - test.exe
